config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
  get "up" => "rails/health#show", as: :rails_health_check
  get '/team', to: 'public#team'
  get '/contact', to: 'public#contact'
 
  get '/home', to: 'home#home'

  resources :gossips do
    resources :comments,  only: [:new, :create, :destroy]
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]  
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :tags, through: :gossip_tags
  has_many :comments
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :content, presence: true

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  def show
    @gossip = Gossip.find(params[:id])
    @comments = @gossip.comments
    @comment_count = @comments.count
  end

  # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  def index
    @gossips = Gossip.all
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(content: params[:content], title: params[:title], user: current_user)
    puts @gossip.title
    if @gossip.save
      redirect_to "/home"
      flash[:success] = "Le gossip a été créé avec succès ! I know you love me... XoXo GossipGirl ;-)"
    else
       # Afficher les erreurs en cas d'échec
      puts "$" * 60
      puts @gossip.errors.full_messages
      puts "$" * 60
      render "/gossips/new"
      flash[:error] = "Échec lors de la création du potin."
      if @gossip.errors[:title].include?("can't be blank")
        flash[:error] += "Le titre du potin ne peut pas être vide."
      end
    
      if @gossip.errors[:title].include?("is too short (minimum is 3 characters)")
        flash[:error] += "Le titre du potin est trop court (le minimum est de 3 caractères)."
      end
    
      if @gossip.errors[:title].include?("is too long (maximum is 14 characters)")
        flash[:error] += "Le titre du potin est trop long (le maximum est de 14 caractères)."
      end
    
      if @gossip.errors[:content].include?("can't be blank")
        flash[:error] += "Le contenu du potin ne peut pas être vide."
      end
    end
    
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip = Gossip.find(params[:id])
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)

    if @gossip.update(gossip_params)
      redirect_to gossip_path(@gossip.id) # Rediriger vers la page du gossip modifié
      flash[:modif_success] = "Le potin a été modifié avec succès."
    else
      # Afficher les erreurs en cas d'échec
      puts "$" * 60
      puts @gossip.errors.full_messages
      puts "$" * 60
      flash[:error] = "Échec lors de la création du potin."
      if @gossip.errors[:title].include?("can't be blank")
        flash[:error] += "Le titre du potin ne peut pas être vide."
      end
    
      if @gossip.errors[:title].include?("is too short (minimum is 3 characters)")
        flash[:error] += "Le titre du potin est trop court (le minimum est de 3 caractères)."
      end
    
      if @gossip.errors[:title].include?("is too long (maximum is 14 characters)")
        flash[:error] += "Le titre du potin est trop long (le maximum est de 14 caractères)."
      end
    
      if @gossip.errors[:content].include?("can't be blank")
        flash[:error] += "Le contenu du potin ne peut pas être vide."
      end
      render 'edit' # En cas d'erreur de validation, réafficher le formulaire d'édition
    end
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    @gossip = Gossip.find_by(id: params[:id])
    @gossip.destroy
    redirect_to gossips_path, notice: 'Le gossip a été supprimé avec succès.'
  end

end

app/views/gossips/edit.html.erb
<h1>Modifier le gossip</h1>

    <!-- alerte post non créé -->
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
     <% end %>
     <!--  -->

<%= form_for @gossip, url: gossip_path(@gossip), method: :patch do |f| %>  
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br /> <br />

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br /> <br />

  <!-- Ne pas afficher le champ user_id, car vous ne voulez pas qu'il soit modifiable -->
  <%= f.hidden_field :user_id, value: @gossip.user_id %>

  <%= submit_tag "Valider les modifications" %>
<% end %>

app/views/gossips/index.html.erb
<!-- bloc index des gossips -->
<div class="my-4 text-center"> <!-- Ajout de marges en haut et en bas, et centrage horizontal -->
    <h3 class="modal-title text-dark fs-4 fs-md-5 mx-1 mx-md-5 mb-5">Liste de tous les gossips <3 </h3>
  </div><div class="container">
  <div class="row">
    <% Gossip.all.each do |gossip| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= gossip.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= gossip.user.first_name %></h6>
            <p class="card-text"><%= "#{gossip.content.split[0, 20].join(' ')}..." %></p>
            <% if current_user %>
              <%= link_to 'Lire la suite', gossip_path(gossip), class: 'card-link' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>Créer un gossip</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
    <!-- alerte post non créé -->
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
     <% end %>
     <!--  -->

 <div class="container mx-3">
    <h1>Raconte nous tout !</h1>

    <p>Balance ton gossip le plus croustillant via le formulaire ci-dessous</p>

    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <div class="mb-3">
        <%= label_tag 'title', 'Titre du Gossip', class: 'form-label' %>
        <%= text_field_tag 'title', @gossip.title, class: 'form-control', id: 'exampleFormControlInput1' %>
      </div>

      <div class="mb-3">
        <%= label_tag 'content', 'Donne-nous un peu plus de détails sur ce gossip ;-)', class: 'form-label' %>
        <%= text_area_tag 'content', @gossip.content, class: 'form-control', id: 'exampleFormControlTextarea1', rows: 3 %>
      </div>

      <%= submit_tag "Envoyer", class: 'btn btn-primary' %>
    <% end %>
</div>
  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
    <title>Show Gossip</title>
  </head>

  <body>
 <!-- alerte post bien modifié -->
  <% if flash[:modif_success] %>
    <div class="alert alert-success">
      <%= flash[:modif_success] %>
    </div>
  <% end %>

  <div class="mt-4"></div> <!-- Ajout de la marge -->
    <div class="container">
      <div class="card text-center">
        <div class="card-header">
          Gossip : <%= @gossip.id %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @gossip.title %></h5>
          <p class="card-text"> <%= @gossip.content %></p>
          <div class="d-flex justify-content-center">      <!-- Boutons avec marge autour -->
            <div class="mx-2">
              <% if current_user == @gossip.user %>
                <%= link_to 'Modifier', edit_gossip_path(@gossip), class: 'btn btn-primary' %>
                </div>
                <div class="mx-2">
                <%= button_to "Supprimer", gossip_path, class: 'btn btn-secondary', form: {data: {turbo_confirm: 'Valider ?'}}, method: :delete %>
              <% end %>

            </div>
          </div>
        </div>
          <div class="card-footer text-muted">
          Ce gossip a été écrit par  <%= link_to @gossip.user.first_name, user_path(@gossip.user) %>  de <%= link_to @gossip.user.city.name , city_path(@gossip.user.city)%> 
        </div>
      </div>
    </div>



<!-- Zone creation commentaires -->
<div class="container-fluid">
  <div class="my-3 mx-3">
    <%= form_tag("/gossips/#{@gossip.id}/comments", method: 'post') do %>
      <p class="comment-form "><%= text_area_tag :content, nil, placeholder: "Votre commentaire ...", rows: 2, cols: 50 %>
        <%= submit_tag "Commenter", class: "button btn btn-outline-info btn-dark btn-sm" %>
      </p>
    <% end %>
  </div>
</div>

<!-- compteur de commentaires -->

<button type="button" class="btn btn-primary position-relative mx-4">
  Commentaires
  <span id="comment-count-badge" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
   <%= @comment_count %>
    <span class="visually-hidden">unread messages</span>
  </span>
</button>

<!-- Zone affichage commentaires -->
  <p class="small text-italic mx-4">Pour info, ce sont des contrepétries ;-)</p><ul class="list-group">
  <% @gossip.comments.each do |comment| %>
    <li class="list-group-item mx-4">
     <%= comment.content %><br>
     <p class="small text-muted text-italic"> Ecrit par <%= comment.user.first_name %>, le <%= comment.updated_at.strftime("%d/%m/%Y") %></p>
      <div class="mb-2 mt-2"> <!-- Ajout de marges en haut et en bas du bouton -->
      <% if current_user == comment.user %>   
        <%= button_to "Supprimer", [@gossip, comment], class: 'btn btn-secondary', form: {data: {turbo_confirm: 'Valider ?'}}, method: :delete %>
      <% end %>
      </div>    
    </li>
   <% end %>

<!-- Bouton Retour -->
  <a href="<%= gossips_path %>">Retour à la liste de gossips</a>


  </body>
</html>