config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
  get "up" => "rails/health#show", as: :rails_health_check
  get '/team', to: 'public#team'
  get '/contact', to: 'public#contact'
 
  get '/home', to: 'home#home'

  resources :gossips do
    resources :comments,  only: [:new, :create, :destroy]
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :tags, through: :gossip_tags
  has_many :comments
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :content, presence: true

end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_many :comments
  has_secure_password
  validates :email, presence: true, uniqueness: true

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
   def show
     @city = City.find(params[:id])
     @users = @city.users
     @gossips = Gossip.joins(:user).where(users: { city_id: @city.id })
     
   end
 
   # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
   def index
     @cities = City.all
   end
 
 
 end
 
 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @gossips = Gossip.all
  end
end

app/controllers/index_controller.rb
class HomeController < ApplicationController
  def index
    Gossip.all
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  def show
    @user = User.find(params[:id])
    if @user #vérifie si @user est défini et n'est pas nil. Si @user est nil, cela signifie qu'aucun utilisateur correspondant à l'ID donné n'a été trouvé dans la base de données.
      if @user.gossips.present? #vérifie si l'utilisateur a des gossips associés. 
        @gossips = @user.gossips #Si l'utilisateur a des gossips associés, cette ligne attribue ces gossips à la variable d'instance @gossips.
      else
        @gossips = [] #nous initialisons @gossips comme un tableau vide pour éviter que @gossips ne soit nil. Cela garantit que vous pouvez itérer sur @gossips sans déclencher d'erreurs.
      end
    else
      # Traitez le cas où l'utilisateur n'a pas été trouvé (par exemple, redirigez vers une page d'erreur)
    end
  end

  # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  def index
    @users = User.all
  end

  def new
  @user = User.new
  end

  def create
    @user = User.new(user_params)
      # par defaut tous les nouveaux user sont a paris. Recherche de la ville de Paris ou création si elle n'existe pas
    paris_city = City.find_or_create_by(name: "Paris", zip_code: "75011")
    @user.city = paris_city
    
    if @user.save
      remember(@user) # Crée le cookie de mémorisation
      log_in(@user) # Connecte l'utilisateur
      redirect_to home_path # Redirige vers la page de connexion 
    else
      # Afficher les erreurs en cas d'échec
      puts "$" * 60
      puts @user.errors.full_messages
      puts "$" * 60
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :city, :age, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/create_gossip_helper.rb
module CreateGossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      # même chose que hier
      current_user = User.find_by(id: session[:user_id])
  
    # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
  
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
  
      if user
  
        # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        if user_authenticated
          log_in user
          current_user = user
        end
  
      end
    end
  end


  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
    
  

end

app/helpers/show_gossip_helper.rb
module ShowGossipHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/index.html.erb
<h1>Liste de toutes les villes</h1>

<ul>
  <% @cities.each do |city| %>
    <li>
      <%= link_to city.name, city_path(city) %>
    </li>
  <% end %>
</ul>

app/views/cities/show.html.erb
<h1>ICI c'est <%= @city.name %> (Code postal : <%= @city.zip_code %>)!!!</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
    </li>
  <% end %>
</ul>

<h2>Gossips de cette ville :</h2>
<ul>
  <% @gossips.each do |gossip| %>
    <li>
      <%= link_to gossip.title, gossip_path(gossip) %> (ID: <%= gossip.id %>)
    </li>
  <% end %>
</ul>

app/views/home/home.html.erb
<header class="jumbotron text-center gringas" style="background-image: url('<%= image_path("gossipgirlcrew.jpeg") %>'); background-size: cover;">
  <div class="modal-static bg-transparent" tabindex="1">
    <div class="texte_image" style="background-image: initial;">
      <div class="modal- bg-transparent d-flex flex-column justify-content-center align-items-center h-100 ">
        <!-- Utilisation des classes Bootstrap pour le dimensionnement automatique -->
        <h1 class="modal-title text-dark fs-3 fs-md-6 mt-4">Bonjour <%= current_user ? current_user.first_name : 'cher visiteur !' %> </h1>
        <h3 class="modal-title text-dark fs-4 fs-md-6 mx-1 mx-md-5 mt-4 mb-4">Tous les potins de la promo THP Autome 2023</h3>
           <!-- Condition pour afficher le bouton si un utilisateur est connecté -->
        <% if current_user %>
          <a href="<%= new_gossip_path %>" class="btn btn-primary btn-lg mb-4">Balance un gossip</a>
        <% end %>
      </div>
    </div>
  </div>
</header>


  

<body>
  <div class="my-4 text-center"> <!-- Ajout de marges en haut et en bas, et centrage horizontal -->
    <h3 class="modal-title text-dark fs-4 fs-md-5 mx-1 mx-md-5 mb-5">Les derniers gossips ...</h3>
  </div>
    <% unless current_user %>
      <p class="text">Connecte-toi pour partager tes potins !</p>
    <% end %>
  <!-- alerte post bien créé -->
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>

  <!-- alerte connexion réussie -->
  <% if flash[:session_success] %>
    <div class="alert alert-success">
      <%= flash[:session_success] %>
    </div>
  <% end %>

  <!-- bloc index des gossips -->

  <div class="container-fluid">

<!-- Bloc index des gossips -->
<div class="container">
  <div class="row">
    <% Gossip.order(created_at: :desc).limit(5).each do |gossip| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= gossip.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= gossip.user.first_name %></h6>
            <p class="card-text"><%= "#{gossip.content.split[0, 20].join(' ')}..." %></p>
            <% if current_user %>
              <%= link_to 'Lire la suite', gossip_path(gossip), class: 'card-link' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

</header>

app/views/users/index.html.erb
<h1>Liste de tous les utilisateurs</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %> (ID: <%= user.id %>)
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_tag url_for(action: 'create'), method: 'post', class: 'mx-2' do %>
  <div class="form-row my-2">
    <div class="col my-2">
      <%= label_tag 'user[first_name]', 'Vos informations personnelles' %>
      <%= text_field_tag 'user[first_name]', nil, class: 'form-control', placeholder: 'Prénom' %>
    </div>
    <div class="col my-2">
      <%= text_field_tag 'user[last_name]', nil, class: 'form-control', placeholder: 'Nom' %>
    </div>
  </div>

  <div class="form-group my-2">
    <%= email_field_tag 'user[email]', nil, class: 'form-control', placeholder: 'Entrez votre adresse email' %>
    <small id="emailHelp" class="form-text text-muted">Nous ne partagerons jamais votre adresse e-mail avec personne d'autre.</small>
  </div>

  <div class="form-group my-2">
    <%= label_tag 'user[city]', 'Où habitez-vous ?' %>
    <%= collection_select(:user, :city_id, City.all, :id, :name, { prompt: 'Sélectionnez une ville' }, class: 'form-control') %>
  </div>

  <div class="form-group my-2">
  <%= label_tag 'user[age]', 'Âge' %>
  <%= number_field_tag 'user[age]', nil, class: 'form-control', placeholder: 'Âge' %>
  </div>

  <div class="form-group my-2">
    <%= label_tag 'user[description]', 'Description' %>
    <%= text_area_tag 'user[description]', nil, class: 'form-control', placeholder: 'Description' %>
  </div>

  <div class="form-group my-2">
    <%= label_tag 'user[password]', 'Définissez votre mot de passe' %>
    <%= password_field_tag 'user[password]', nil, class: 'form-control', placeholder: 'Mot de passe' %>
  </div>

  <div class="form-group my-2">
    <%= password_field_tag 'user[password_confirmation]', nil, class: 'form-control', placeholder: 'Confirmer le mot de passe' %>
  </div>

  <div class="field my-2">
    <%= label_tag :remember_me, 'Se souvenir de moi' %>
    <%= check_box_tag :remember_me %>
  </div>

  <%= submit_tag 'Valider', class: 'btn btn-primary my-2' %>
  <small id="already_member" class="form-text text-muted my-2">
    <%= link_to 'Déjà membre', new_session_path %>
  </small>
<% end %>

app/views/users/show.html.erb
<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>

<p>ID: <%= @user.id %></p>
<p>Description : <%= @user.description %></p>
<p>E-mail : <%= @user.email %></p>
<p>Âge : <%= @user.age %></p>

<p>Ville : <%= @user.city.name %> (<%= @user.city.zip_code %>)</p>
<h2>Gossips écrits <%= @user.first_name %></h2>
<ul>
  <% @gossips.each do |gossip| %>
    <li>
      <%= link_to gossip.title, gossip_path(gossip) %> (ID: <%= gossip.id %>)
    </li>
  <% end %>
</ul>