config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
  get "up" => "rails/health#show", as: :rails_health_check
  get '/team', to: 'public#team'
  get '/contact', to: 'public#contact'
 
  get '/home', to: 'home#home'

  resources :gossips do
    resources :comments,  only: [:new, :create, :destroy]
  end

  resources :users
  resources :cities

  resources :sessions, only: [:new, :create, :destroy]  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :tags, through: :gossip_tags
  has_many :comments
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :content, presence: true

end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_many :comments
  has_secure_password
  validates :email, presence: true, uniqueness: true

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @gossips = Gossip.all
  end
end

app/controllers/index_controller.rb
class HomeController < ApplicationController
  def index
    Gossip.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  def show
    @user = User.find(params[:id])
    if @user #vérifie si @user est défini et n'est pas nil. Si @user est nil, cela signifie qu'aucun utilisateur correspondant à l'ID donné n'a été trouvé dans la base de données.
      if @user.gossips.present? #vérifie si l'utilisateur a des gossips associés. 
        @gossips = @user.gossips #Si l'utilisateur a des gossips associés, cette ligne attribue ces gossips à la variable d'instance @gossips.
      else
        @gossips = [] #nous initialisons @gossips comme un tableau vide pour éviter que @gossips ne soit nil. Cela garantit que vous pouvez itérer sur @gossips sans déclencher d'erreurs.
      end
    else
      # Traitez le cas où l'utilisateur n'a pas été trouvé (par exemple, redirigez vers une page d'erreur)
    end
  end

  # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  def index
    @users = User.all
  end

  def new
  @user = User.new
  end

  def create
    @user = User.new(user_params)
      # par defaut tous les nouveaux user sont a paris. Recherche de la ville de Paris ou création si elle n'existe pas
    paris_city = City.find_or_create_by(name: "Paris", zip_code: "75011")
    @user.city = paris_city
    
    if @user.save
      remember(@user) # Crée le cookie de mémorisation
      log_in(@user) # Connecte l'utilisateur
      redirect_to home_path # Redirige vers la page de connexion 
    else
      # Afficher les erreurs en cas d'échec
      puts "$" * 60
      puts @user.errors.full_messages
      puts "$" * 60
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :city, :age, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/create_gossip_helper.rb
module CreateGossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      # même chose que hier
      current_user = User.find_by(id: session[:user_id])
  
    # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
  
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
  
      if user
  
        # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        if user_authenticated
          log_in user
          current_user = user
        end
  
      end
    end
  end


  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end
    
  

end

app/helpers/show_gossip_helper.rb
module ShowGossipHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>MyGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Les balises link et script doivent être incluses dans le head -->
  <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- surcouche CSS -->

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/0c57e11e06.js" crossorigin="anonymous"></script>
    

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="application.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-turbo="false">
    <!-- Condition pour afficher la navbar si l'utilisateur est connecté -->
    <% if current_user %>
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
          <%= link_to "/home", class: "d-inline-flex link-body-emphasis text-decoration-none" do %>
            <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap">
              <use xlink:href="#bootstrap"></use>
            </svg>
          <% end %>
        </div>
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <%= link_to "The Gossip Project", home_path, class: "nav-link px-2 link-secondary" %>
          <%= link_to "Liste des gossips", gossips_path, class: "nav-link px-2" %>
          <%= link_to "Liste des gossipers", users_path, class: "nav-link px-2" %>
          <%= link_to "Notre équipe", team_path, class: "nav-link px-2" %>
          <%= link_to "Contact", contact_path, class: "nav-link px-2" %>
          <%= button_to "Déconnexion", session_path(session.id), method: :delete, class: "btn-custom-logout" %>
        </ul>
      </div>
    <% else %>
      <!-- Liens de navigation pour les utilisateurs non connectés -->
      <div class="col-md-3 text-end">
        <%= link_to "Connexion", new_session_path, class: "btn btn-outline-primary me-2" %>
        <%= link_to "Inscription", new_user_path, class: "btn btn-primary" %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>